#!/usr/bin/env python
# -*- coding: utf-8 -*-

""" jmLightToolkit UI. Genererated by pyside2-uic. """

from PySide2 import QtCore, QtGui, QtWidgets


class Ui_widget_root(object):
    def setupUi(self, widget_root):
        widget_root.setObjectName("widget_root")
        widget_root.resize(350, 600)
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(widget_root)
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.tabWidget = QtWidgets.QTabWidget(widget_root)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_lighting = QtWidgets.QWidget()
        self.tab_lighting.setObjectName("tab_lighting")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_lighting)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_lighting)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 306, 893))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setContentsMargins(3, 0, 3, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(3)
        self.verticalLayout_4.setContentsMargins(-1, 3, -1, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_lights = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_lights.sizePolicy().hasHeightForWidth())
        self.label_lights.setSizePolicy(sizePolicy)
        self.label_lights.setMinimumSize(QtCore.QSize(0, 16))


class Ui_widget_lightOptimizerItem(object):
    def setupUi(self, widget_lightOptimizerItem):
        widget_lightOptimizerItem.setObjectName("widget_lightOptimizerItem")
        widget_lightOptimizerItem.resize(320, 71)
        self.horizontalLayout = QtWidgets.QHBoxLayout(widget_lightOptimizerItem)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Icon = QtWidgets.QPushButton(widget_lightOptimizerItem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Icon.sizePolicy().hasHeightForWidth())
        self.pushButton_Icon.setSizePolicy(sizePolicy)
        self.pushButton_Icon.setMinimumSize(QtCore.QSize(40, 40))
        self.pushButton_Icon.setText("")
        self.pushButton_Icon.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_Icon.setObjectName("pushButton_Icon")
        self.horizontalLayout.addWidget(self.pushButton_Icon)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_lightname = QtWidgets.QLabel(widget_lightOptimizerItem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_lightname.sizePolicy().hasHeightForWidth())
        self.label_lightname.setSizePolicy(sizePolicy)
        self.label_lightname.setObjectName("label_lightname")
        self.verticalLayout.addWidget(self.label_lightname)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_attribute = QtWidgets.QLabel(widget_lightOptimizerItem)
        self.label_attribute.setObjectName("label_attribute")
        self.horizontalLayout_2.addWidget(self.label_attribute)
        self.doubleSpinBox_attributeValue = QtWidgets.QDoubleSpinBox(widget_lightOptimizerItem)
        self.doubleSpinBox_attributeValue.setObjectName("doubleSpinBox_attributeValue")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_attributeValue)
        self.pushButton_setValue = QtWidgets.QPushButton(widget_lightOptimizerItem)
        self.pushButton_setValue.setObjectName("pushButton_setValue")
        self.horizontalLayout_2.addWidget(self.pushButton_setValue)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout)

        self.retranslateUi(widget_lightOptimizerItem)
        QtCore.QMetaObject.connectSlotsByName(widget_lightOptimizerItem)

    def retranslateUi(self, widget_lightOptimizerItem):
        widget_lightOptimizerItem.setWindowTitle(QtWidgets.QApplication.translate("widget_lightOptimizerItem", "Form", None, -1))
        self.pushButton_Icon.setShortcut(QtWidgets.QApplication.translate("widget_lightOptimizerItem", "Ctrl+S", None, -1))
        self.label_lightname.setText(QtWidgets.QApplication.translate("widget_lightOptimizerItem", "lightName", None, -1))
        self.label_attribute.setText(QtWidgets.QApplication.translate("widget_lightOptimizerItem", "attribute", None, -1))
        self.pushButton_setValue.setText(QtWidgets.QApplication.translate("widget_lightOptimizerItem", "Set Value", None, -1))


class Ui_widget_unusedFiltersList(object):
    def setupUi(self, widget_unusedFiltersList):
        widget_unusedFiltersList.setObjectName("widget_unusedFiltersList")
        widget_unusedFiltersList.resize(300, 600)
        self.verticalLayout = QtWidgets.QVBoxLayout(widget_unusedFiltersList)
        self.verticalLayout.setSpacing(9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_disconnectedFilters = QtWidgets.QLabel(widget_unusedFiltersList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_disconnectedFilters.sizePolicy().hasHeightForWidth())
        self.label_disconnectedFilters.setSizePolicy(sizePolicy)
        self.label_disconnectedFilters.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_disconnectedFilters.setFont(font)
        self.label_disconnectedFilters.setStyleSheet("background:rgb(20,230,150);")
        self.label_disconnectedFilters.setIndent(5)
        self.label_disconnectedFilters.setObjectName("label_disconnectedFilters")
        self.verticalLayout_2.addWidget(self.label_disconnectedFilters)
        self.listWidget_disconnectedFilters = QtWidgets.QListWidget(widget_unusedFiltersList)
        self.listWidget_disconnectedFilters.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget_disconnectedFilters.setAlternatingRowColors(True)
        self.listWidget_disconnectedFilters.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_disconnectedFilters.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget_disconnectedFilters.setModelColumn(0)
        self.listWidget_disconnectedFilters.setObjectName("listWidget_disconnectedFilters")
        self.verticalLayout_2.addWidget(self.listWidget_disconnectedFilters)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_nullFilters = QtWidgets.QLabel(widget_unusedFiltersList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_nullFilters.sizePolicy().hasHeightForWidth())
        self.label_nullFilters.setSizePolicy(sizePolicy)
        self.label_nullFilters.setMinimumSize(QtCore.QSize(0, 16))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_nullFilters.setFont(font)
        self.label_nullFilters.setStyleSheet("background:rgb(20,200,180);")
        self.label_nullFilters.setMargin(0)
        self.label_nullFilters.setIndent(5)
        self.label_nullFilters.setObjectName("label_nullFilters")
        self.verticalLayout_3.addWidget(self.label_nullFilters)
        self.listWidget_nullFilters = QtWidgets.QListWidget(widget_unusedFiltersList)
        self.listWidget_nullFilters.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget_nullFilters.setAlternatingRowColors(True)
        self.listWidget_nullFilters.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_nullFilters.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget_nullFilters.setModelColumn(0)
        self.listWidget_nullFilters.setObjectName("listWidget_nullFilters")
        self.verticalLayout_3.addWidget(self.listWidget_nullFilters)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_delete = QtWidgets.QPushButton(widget_unusedFiltersList)
        self.pushButton_delete.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_delete.setObjectName("pushButton_delete")
        self.horizontalLayout.addWidget(self.pushButton_delete)
        self.pushButton_cancel = QtWidgets.QPushButton(widget_unusedFiltersList)
        self.pushButton_cancel.setMinimumSize(QtCore.QSize(0, 25))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(widget_unusedFiltersList)
        QtCore.QMetaObject.connectSlotsByName(widget_unusedFiltersList)

    def retranslateUi(self, widget_unusedFiltersList):
        widget_unusedFiltersList.setWindowTitle(QtWidgets.QApplication.translate("widget_unusedFiltersList", "Form", None, -1))
        self.label_disconnectedFilters.setText(QtWidgets.QApplication.translate("widget_unusedFiltersList", "<html><head/><body><p><span style=\" color:#ffffff;\">Disconnected filters</span></p></body></html>", None, -1))
        self.label_nullFilters.setText(QtWidgets.QApplication.translate("widget_unusedFiltersList", "<html><head/><body><p><span style=\" color:#ffffff;\">Null filters</span></p></body></html>", None, -1))
        self.pushButton_delete.setText(QtWidgets.QApplication.translate("widget_unusedFiltersList", "Delete", None, -1))
        self.pushButton_cancel.setText(QtWidgets.QApplication.translate("widget_unusedFiltersList", "Cancel", None, -1))


class Ui_widget_unusedFiltersItem(object):
    def setupUi(self, widget_unusedFiltersItem):
        widget_unusedFiltersItem.setObjectName("widget_unusedFiltersItem")
        widget_unusedFiltersItem.resize(300, 50)
        self.horizontalLayout = QtWidgets.QHBoxLayout(widget_unusedFiltersItem)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_filterName = QtWidgets.QLabel(widget_unusedFiltersItem)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_filterName.sizePolicy().hasHeightForWidth())
        self.label_filterName.setSizePolicy(sizePolicy)
        self.label_filterName.setMinimumSize(QtCore.QSize(50, 0))
        self.label_filterName.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_filterName.setObjectName("label_filterName")
        self.horizontalLayout.addWidget(self.label_filterName)
        self.pushButton_select = QtWidgets.QPushButton(widget_unusedFiltersItem)
        self.pushButton_select.setMinimumSize(QtCore.QSize(25, 25))
        self.pushButton_select.setMaximumSize(QtCore.QSize(25, 25))
        self.pushButton_select.setText("")
        self.pushButton_select.setObjectName("pushButton_select")
        self.horizontalLayout.addWidget(self.pushButton_select)

        self.retranslateUi(widget_unusedFiltersItem)
        QtCore.QMetaObject.connectSlotsByName(widget_unusedFiltersItem)

    def retranslateUi(self, widget_unusedFiltersItem):
        widget_unusedFiltersItem.setWindowTitle(QtWidgets.QApplication.translate("widget_unusedFiltersItem", "Form", None, -1))
        self.label_filterName.setText(QtWidgets.QApplication.translate("widget_unusedFiltersItem", "filename", None, -1))
